logger_cfg : 
  run_name : 
  project_name : 


env_cfg : 

  env_name : Hopper-v4 
  normalize_obs : True
  reward_scale : 270.
  reward_shift : 0.
  discount : 0.99
  

algo_cfg :
  
  learning_rate : 0.01
  sigma : 0.025 ### 
  n_info : 16
  top_directions : 4 ## ARS
  num_rollouts : 1
  num_learning_steps : 330
  
  
  
policy_cfg: 

  hidden_dims: ()
  output_activation: tanh
  use_bias : False
  
















