logger_cfg : 
  run_name : 
  project_name : 


env_cfg : 

  env_name : Ant-v4 
  normalize_obs : True
  reward_scale : 400.
  reward_shift : 0.
  discount : 0.99
  

algo_cfg :
  
  learning_rate : 0.01
  sigma : 0.025 ### 
  n_max : 75
  n_info : 24
  n_parallel : 1
  num_rollouts : 1
  num_rollouts_center : 5
  num_learning_steps : 1000
  



kernel_cfg:

  use_ard : True
  lengthscale_bound : [0.000625,0.0125]
  


policy_cfg: 

  hidden_dims: ()
  output_activation : "tanh"
  use_bias : False
  








